[package]
name = "soundkit-aac"
version = "0.1.0"
edition = "2021"

[dependencies]
access-unit = { git = "https://github.com/wavey-ai/access-unit.git" }
fdk-aac = { git = "https://github.com/wavey-ai/fdk-aac-rs.git" }

soundkit = { path = "../soundkit" }
tracing = "0.1.40"
