[package]
name = "soundkit"
version = "0.9.4"
edition = "2021"
license = "MIT"
description = "Audio format optimised for low-latency audio."
repository = "https://github.com/wavey-ai/soundkit"
readme = "README.md"

[dependencies]
js-sys = { version = "0.3.64", optional = true }
libopus = { path = "../opus-rs", optional = true }
web-sys = { version = "0.3.64", optional = true, features = ["Worker"] }
wasm-bindgen = { version = "0.2.87", optional = true }
rubato = "0.14.1"
byteorder = "1.5.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["libopus"]
wasm = ["js-sys", "web-sys", "wasm-bindgen"]
