[package]
name = "soundkit"
version = "0.9.4"
edition = "2021"
license = "MIT"
description = "Audio format optimised for low-latency audio."
repository = "https://github.com/wavey-ai/soundkit"
readme = "README.md"
wasm-bindgen = "0.2.87"

[dependencies]
js-sys = { version = "0.3.64", optional = true }
libopus = { path = "../opus-rs", optional = true }
web-sys = { version = "0.3.64", optional = true }
[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["libopus"]
wasm = ["js-sys", "web-sys"]
