[package]
name = "soundkit"
version = "0.9.0"
edition = "2021"
license = "MIT"
description = "Audio format optimised for low-latency audio."
repository = "https://github.com/wavey-ai/soundkit"
readme = "README.md"

[dependencies]
opus = "0.3.0"
structopt = "0.3"

[[bin]]
name = "soundkit"
path = "src/main.rs"
