[package]
name = "soundkit"
version = "0.9.4"
edition = "2021"
license = "MIT"
description = "Audio format optimised for low-latency audio."
repository = "https://github.com/wavey-ai/soundkit"
readme = "README.md"

[dependencies]
libopus = { path = "../opus-rs" }

#[[bin]]
#name = "soundkit"
#path = "src/main.rs"
